/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hammer;

import java.net.URL;
import java.sql.*;
import javax.sound.sampled.*;
import javax.swing.*;

/**
 *
 * @author Mohit
 */
public class Existing_user extends javax.swing.JFrame {

    static String id = "";
    int temp ; 
    /**
     * Creates new form Existing_user
     */
    public Existing_user() {
        initComponents();
        jTextField1.requestFocusInWindow();
        setLocationRelativeTo(null);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hammer Mania-Login Menu");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("Enter your User_No");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 110, 110, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(500, 110, 110, 30);

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jButton1.setText("Start the Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(425, 170, 110, 30);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User Log-in Menu");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 10, 380, 60);

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hammer/back.png"))); // NOI18N
        jButton2.setToolTipText("Back to home Page");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton2KeyReleased(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 40, 30);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hammer/panda2.png"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 650, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        id = jTextField1.getText();
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter your User_No");
        }
        else
        {
            temp = 1;
            sound();
            
            int count=0;
            new Database_Connection();
            try 
            {
                Statement s = Database_Connection.con.createStatement();
                ResultSet rs = s.executeQuery("select * from user_info where User_No = '"+jTextField1.getText()+"' ");
                
                while(rs.next())
                {
                    count++;
                }
                if(count == 1)
                {
                    New_user.User_id = Integer.parseInt(jTextField1.getText());
                    
                    Game f1 = new Game();
                    Thread t1 = new Thread(f1 , "Thread");
                    f1.setThread(t1);
                    t1.start();
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "You are not registered");
                }
            } 
            catch (Exception e) 
            {
                System.out.println("Error because of: "+e);
            }    
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        temp = 0;
        sound();
        new Home_Page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        id = jTextField1.getText();
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter your User_No");
        }
        else
        {
            temp = 1;
            sound();
            
            int count=0;
            new Database_Connection();
            try 
            {
                Statement s = Database_Connection.con.createStatement();
                ResultSet rs = s.executeQuery("select * from user_info where User_No = '"+jTextField1.getText()+"' ");
                
                while(rs.next())
                {
                    count++;
                }
                if(count == 1)
                {
                    New_user.User_id = Integer.parseInt(jTextField1.getText());
         
                    Game f1 = new Game();
                    Thread t1 = new Thread(f1 , "Thread");
                    f1.setThread(t1);
                    t1.start();
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "You are not registered");
                }
            } 
            catch (Exception e) 
            {
                System.out.println("Error because of: "+e);
            }    
        }
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyReleased
        temp = 0;
        sound();
        new Home_Page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2KeyReleased

    void sound()
    {
       try {
         // Open an audio input stream.
         URL url;
         if(temp == 0)
         {
             url = this.getClass().getClassLoader().getResource("Exit.wav");
         }
         else
         {
             url = this.getClass().getClassLoader().getResource("Entry.wav");
         }
         AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
         // Get a sound clip resource.
         Clip clip = AudioSystem.getClip();
         // Open audio clip and load samples from the audio input stream.
         clip.open(audioIn);
         clip.start();
      }
       catch(Exception e)
       {
           System.err.println("Error because of: "+e);
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Existing_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Existing_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Existing_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Existing_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
  
                new Existing_user().setVisible(true);
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
