/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hammer;

import static Hammer.Database_Connection.con;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.*;
import javax.sound.sampled.*;
import javax.swing.*;

/**
 *
 * @author Mohit
 */
public class New_user extends javax.swing.JFrame {

    /**
     * Creates new form New_user
     */
    
    static int User_id;
    int temp;
    public New_user() {
        
        initComponents();
         jTextField1.requestFocusInWindow();
        setLocationRelativeTo(null);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hammer Mania-SignUp Menu");
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(null);

        jLabel1.setText("Enter Your Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 130, 100, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(400, 130, 140, 30);

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jButton1.setText("Submit");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 290, 90, 40);

        jLabel2.setText("Enter your Age");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 170, 90, 14);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(400, 170, 140, 30);

        jLabel3.setText("Gender");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 210, 80, 14);

        jRadioButton1.setText("Male");
        jRadioButton1.setOpaque(false);
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(400, 210, 80, 23);

        jRadioButton2.setText("Female");
        jRadioButton2.setOpaque(false);
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(400, 240, 80, 20);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sign up Menu");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 20, 380, 60);

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hammer/back.png"))); // NOI18N
        jButton2.setToolTipText("back to Home Page");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton2KeyReleased(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 40, 30);

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hammer/panda1.png"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 580, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter your Name");
        }
        else if(jTextField2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter your Age");
        }
        else if(!jRadioButton1.isSelected() && !jRadioButton2.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select your gender");
        }
        else
        {
            temp = 1;
            sound();
            
            int count = 10001 , games_played=0;
            String gender , status="Not Started";
            if(jRadioButton1.isSelected())
            {
                gender = "Male";
            }
            else
            {
                gender = "Female";
            }
            
            new Database_Connection();
            try
            {
                Statement s = Database_Connection.con.createStatement();
                ResultSet rs = s.executeQuery("Select * from user_info");
                while(rs.next())
                {
                    count++;
                }
                s.executeUpdate(" insert into user_info(User_No , Name , age ,gender ) values ('"+count+"' ,'"+jTextField1.getText()+"' , '"+jTextField2.getText()+"' , '"+gender+"') ");
                s.executeUpdate(" insert into user_status(User_No , games_played , status ) values ('"+count+"' , '"+games_played+"' , '"+status+"' ) ");
                JOptionPane.showMessageDialog(null,"Your User_No is: "+count + ". Keep it remember");

                User_id = count;
                jTextField1.setText("");
                jTextField2.setText("");
                jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false); 
            }
            catch(Exception e)
            {
                System.out.println("Error because of: "+e);
            }        
            Home_Page.gamenumber = 1;
            new Rules().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        temp = 0;
        sound();
        new Home_Page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter your Name");
        }
        else if(jTextField2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter your Age");
        }
        else if(!jRadioButton1.isSelected() && !jRadioButton2.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please Select your gender");
        }
        else
        {
            temp = 1;
            sound();
            
            int count = 10001 , games_played=0;
            String gender , status="Not Started";
            if(jRadioButton1.isSelected())
            {
                gender = "Male";
            }
            else
            {
                gender = "Female";
            }
            
            new Database_Connection();
            try
            {
                Statement s = Database_Connection.con.createStatement();
                
                ResultSet rs = s.executeQuery("Select * from user_info");
                while(rs.next())
                {
                    count++;
                }
                s.executeUpdate(" insert into user_info(User_No , Name , age ,gender ) values ('"+count+"' ,'"+jTextField1.getText()+"' , '"+jTextField2.getText()+"' , '"+gender+"') ");
                s.executeUpdate(" insert into user_status(User_No , games_played , status ) values ('"+count+"' , '"+games_played+"' , '"+status+"' ) ");
                JOptionPane.showMessageDialog(null,"Your User_No is: "+count + ". Keep it remember");

                User_id = count;
                System.err.println(User_id);
                jTextField1.setText("");
                jTextField2.setText("");
                jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false); 
            }
            catch(Exception e)
            {
                System.out.println("Error because of: "+e);
            }        
            Home_Page.gamenumber = 1;
            new Rules().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyReleased
        temp = 0;
        sound();
        new Home_Page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2KeyReleased

    void sound()
    {
       try {
         // Open an audio input stream.
         URL url;
         if(temp == 0)
         {
             url = this.getClass().getClassLoader().getResource("Exit.wav");
         }
         else
         {
             url = this.getClass().getClassLoader().getResource("Gun.wav");
         }
         AudioInputStream audioIn = AudioSystem.getAudioInputStream(url);
         // Get a sound clip resource.
         Clip clip = AudioSystem.getClip();
         // Open audio clip and load samples from the audio input stream.
         clip.open(audioIn);
         clip.start();
      }
       catch(Exception e)
       {
           System.err.println("Error because of: "+e);
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
                new New_user().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
